/**
 * API contract types shared between the FastAPI backend and the Next.js web app.
 * Backend serializes into these shapes; the frontend never recomputes them.
 */

export * from "./constants";

/** Chat request body for `POST /api/query`. */
export interface QueryRequest {
  /** User question text. */
  query: string;
  /** Chat session id (UUID) generated by the client. */
  session_id?: string;
  /** ISO 8601 effective date used to filter documents by `effective_date`. */
  as_of?: string;
  /** Recent conversation turns (client keeps at most 4 rounds). */
  history?: QueryHistoryItem[];
}

export type QueryHistoryRole = "user" | "assistant";

export interface QueryHistoryItem {
  role: QueryHistoryRole;
  content: string;
}

/** Document source cited in an answer. */
export interface Source {
  doc_id: string;
  title: string;
  section?: string;
  effective_from?: string;
  kind: string;
}

/** Legal fact extracted from sources, with evidence. */
export interface FactEvidence {
  fe_id: string;
  subject: string;
  policy_key?: string;
  fields: Record<string, number | string | null>;
  note?: string;
}

/** Nearby amenity/landmark from the maps leg (Google Places or static fallback). */
export interface NearbyPlace {
  name: string;
  kinds: string[];
  lat: number;
  lng: number;
  distance_m?: number;
  address?: string;
  rating?: number;
}

export type Confidence = "HIGH" | "MEDIUM" | "LOW";

export type StructuredPath = "spec" | "nl2sql" | "none";

export interface QueryResponseRouting {
  needs_rag: boolean;
  needs_sql: boolean;
  structured_path: StructuredPath;
}

/** Non-streaming response of `POST /api/query`. */
export interface QueryResponse {
  answer: string;
  sources: Source[];
  facts: FactEvidence[];
  places: NearbyPlace[];
  confidence: Confidence;
  requires_review: boolean;
  routing: QueryResponseRouting;
  trace_id: string;
  latency_ms: number;
}

export type SseEventName = "places" | "sources" | "facts" | "token" | "done" | "error";

/** A single event in the SSE stream of `POST /api/query`. */
export interface SseEvent {
  event: SseEventName;
  data: unknown;
}

/* ------------------------------------------------------------------ */
/* VND currency formatting — single source of truth for money display. */
/* ------------------------------------------------------------------ */

const vndFormatter = new Intl.NumberFormat("vi-VN", {
  maximumFractionDigits: 0,
});

/**
 * Format a number as a VND string using the vi-VN locale.
 * Example: 1_500_000_000 -> "1.500.000.000đ".
 */
export function formatVND(value: number): string {
  return `${vndFormatter.format(value)}đ`;
}
